# Generated by Django 5.2.6 on 2025-11-28 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(blank=True, choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large'), ('XXL', 'XXL'), ('Regular', 'Regular')], help_text="Leave blank if product doesn't have sizes", max_length=20, null=True),
        ),
    ]
