# Generated by Django 5.2.6 on 2025-11-29 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_set_created_at_auto_now_add'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
