# Generated by Django 5.2.6 on 2025-11-30 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_product_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='size',
            field=models.CharField(blank=True, choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large'), ('XXL', 'XXL'), ('Regular', 'Regular')], max_length=20, null=True),
        ),
    ]
